version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nk_admin
      MONGO_INITDB_ROOT_PASSWORD: 9130
    volumes:
      - mymongo-data:/data/db #no space should be there
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nk_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 9130
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  mymongo-data:
    driver: local
